const fs = require('fs');
const path = require('path');

// Raw Table of 400 Medicines
const MEDICINES_RAW = [
  { id: 1, name: 'Paracetamol', group: 'Analgesic/antipyretic', use: 'Fever and mild pain', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Oral tablets; oral liquid; suppository' },
  { id: 2, name: 'Ibuprofen', group: 'NSAID analgesic', use: 'Pain, fever, inflammation', category: 'Daily Life & Primary Care', rx: 'OTC/prescription depending on strength/country', form: 'Tablets/capsules; oral liquid; topical forms' },
  { id: 3, name: 'Naproxen', group: 'NSAID analgesic', use: 'Pain and inflammation', category: 'Daily Life & Primary Care', rx: 'Often prescription; some strengths OTC', form: 'Tablets; oral suspension' },
  { id: 4, name: 'Diclofenac', group: 'NSAID analgesic', use: 'Musculoskeletal pain and inflammation', category: 'Daily Life & Primary Care', rx: 'Often prescription', form: 'Tablets; gel; injection' },
  { id: 5, name: 'Aspirin', group: 'Antiplatelet/NSAID', use: 'Pain/fever; antiplatelet use', category: 'Daily Life & Primary Care', rx: 'OTC for some uses; medical guidance for antiplatelet use', form: 'Tablets' },
  { id: 6, name: 'Cetirizine', group: 'Antihistamine', use: 'Allergy symptoms', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Tablets; oral liquid' },
  { id: 7, name: 'Loratadine', group: 'Antihistamine', use: 'Allergy symptoms', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Tablets; oral liquid' },
  { id: 8, name: 'Fexofenadine', group: 'Antihistamine', use: 'Allergic rhinitis and hives', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral suspension' },
  { id: 9, name: 'Chlorpheniramine', group: 'Antihistamine', use: 'Allergy and cold symptoms', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral liquid' },
  { id: 10, name: 'Diphenhydramine', group: 'Antihistamine', use: 'Allergy symptoms; short-term symptom relief', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral liquid; topical' },
  { id: 11, name: 'Dextromethorphan', group: 'Cough suppressant', use: 'Dry cough', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Syrup; lozenges; capsules' },
  { id: 12, name: 'Guaifenesin', group: 'Expectorant', use: 'Chest congestion with mucus', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Syrup; tablets' },
  { id: 13, name: 'Ambroxol', group: 'Mucolytic', use: 'Productive cough with thick mucus', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; syrup; lozenges' },
  { id: 14, name: 'Bromhexine', group: 'Mucolytic', use: 'Productive cough with thick mucus', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; syrup' },
  { id: 15, name: 'Saline nasal spray', group: 'Nasal saline', use: 'Nasal dryness and congestion', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Nasal spray/drops' },
  { id: 16, name: 'Oxymetazoline', group: 'Topical nasal decongestant', use: 'Short-term nasal congestion', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Nasal spray/drops' },
  { id: 17, name: 'Phenylephrine', group: 'Decongestant', use: 'Nasal congestion', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral liquid; nasal products' },
  { id: 18, name: 'Omeprazole', group: 'Proton-pump inhibitor', use: 'Acid reflux and dyspepsia', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Capsules/tablets' },
  { id: 19, name: 'Famotidine', group: 'H2-receptor blocker', use: 'Heartburn and acid-related symptoms', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral liquid' },
  { id: 20, name: 'Calcium carbonate', group: 'Antacid', use: 'Heartburn and acid indigestion', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Chewable tablets; suspension' },
  { id: 21, name: 'Magnesium hydroxide', group: 'Antacid/laxative', use: 'Heartburn; constipation', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Suspension; chewable forms' },
  { id: 22, name: 'Aluminium hydroxide', group: 'Antacid', use: 'Heartburn and acid indigestion', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Suspension; tablets' },
  { id: 23, name: 'Simethicone', group: 'Antiflatulent', use: 'Gas and bloating', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Chewable tablets; oral liquid; capsules' },
  { id: 24, name: 'Loperamide', group: 'Antidiarrheal', use: 'Short-term diarrhea control', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Capsules; tablets' },
  { id: 25, name: 'Oral rehydration salts', group: 'Rehydration therapy', use: 'Prevention/treatment of dehydration from diarrhea', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Oral powder for solution' },
  { id: 26, name: 'Psyllium', group: 'Bulk-forming laxative', use: 'Constipation and fiber supplementation', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Powder; granules; capsules' },
  { id: 27, name: 'Polyethylene glycol', group: 'Osmotic laxative', use: 'Constipation', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Powder for solution' },
  { id: 28, name: 'Bisacodyl', group: 'Stimulant laxative', use: 'Short-term constipation', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Tablets; suppository' },
  { id: 29, name: 'Docusate', group: 'Stool softener', use: 'Constipation', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Capsules; liquid' },
  { id: 30, name: 'Ferrous sulfate', group: 'Iron supplement', use: 'Iron deficiency', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets/capsules; liquid' },
  { id: 31, name: 'Folic acid', group: 'Vitamin supplement', use: 'Folate deficiency; pregnancy supplementation', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral liquid' },
  { id: 32, name: 'Vitamin D3 (cholecalciferol)', group: 'Vitamin supplement', use: 'Vitamin D deficiency prevention/treatment', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; capsules; oral drops' },
  { id: 33, name: 'Calcium carbonate + vitamin D', group: 'Mineral/vitamin supplement', use: 'Calcium and vitamin D supplementation', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; chewables' },
  { id: 34, name: 'Vitamin B12 (cyanocobalamin)', group: 'Vitamin supplement', use: 'Vitamin B12 deficiency', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; oral liquid; injection' },
  { id: 35, name: 'Ascorbic acid (vitamin C)', group: 'Vitamin supplement', use: 'Vitamin C supplementation', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Tablets; chewables; oral liquid' },
  { id: 36, name: 'Zinc sulfate', group: 'Mineral supplement', use: 'Zinc deficiency; supplementation', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets/capsules; syrup' },
  { id: 37, name: 'Povidone-iodine', group: 'Antiseptic', use: 'Minor skin antisepsis', category: 'Daily Life & Primary Care', rx: 'OTC in many countries', form: 'Solution; ointment' },
  { id: 38, name: 'Chlorhexidine', group: 'Antiseptic', use: 'Skin/oral antisepsis', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Solution; mouthwash; topical products' },
  { id: 39, name: 'Hydrogen peroxide', group: 'Topical antiseptic', use: 'Limited minor wound cleansing', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Topical solution' },
  { id: 40, name: 'Calamine', group: 'Topical protectant', use: 'Itching and minor skin irritation', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Lotion' },
  { id: 41, name: 'Zinc oxide', group: 'Skin protectant', use: 'Irritant dermatitis and skin protection', category: 'Daily Life & Primary Care', rx: 'OTC', form: 'Cream; ointment; paste' },
  { id: 42, name: 'Hydrocortisone 1%', group: 'Topical corticosteroid', use: 'Mild inflammatory/itchy skin conditions', category: 'Daily Life & Primary Care', rx: 'OTC in some countries', form: 'Cream; ointment' },
  { id: 43, name: 'Clotrimazole', group: 'Topical antifungal', use: 'Superficial fungal skin infections', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Cream; solution; vaginal preparations' },
  { id: 44, name: 'Miconazole', group: 'Topical antifungal', use: 'Superficial fungal infections', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Cream; powder; vaginal preparations' },
  { id: 45, name: 'Terbinafine', group: 'Antifungal', use: 'Dermatophyte skin infections', category: 'Daily Life & Primary Care', rx: 'Topical often OTC; oral usually prescription', form: 'Cream; gel; tablets' },
  { id: 46, name: 'Acyclovir', group: 'Antiviral', use: 'Herpes virus infections', category: 'Daily Life & Primary Care', rx: 'Usually prescription; topical varies', form: 'Cream; tablets; injection' },
  { id: 47, name: 'Permethrin', group: 'Antiparasitic', use: 'Scabies and lice', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Cream; lotion' },
  { id: 48, name: 'Dimenhydrinate', group: 'Antiemetic', use: 'Motion sickness and nausea', category: 'Daily Life & Primary Care', rx: 'OTC/prescription varies', form: 'Tablets; chewables; injection' },
  { id: 49, name: 'Ondansetron', group: 'Antiemetic', use: 'Nausea and vomiting', category: 'Daily Life & Primary Care', rx: 'Prescription', form: 'Tablets/ODT; injection; oral solution' },
  { id: 50, name: 'Promethazine', group: 'Antihistamine/antiemetic', use: 'Allergy symptoms and nausea', category: 'Daily Life & Primary Care', rx: 'Prescription', form: 'Tablets; oral liquid; injection' },
  { id: 51, name: 'Dimethindene', group: 'Antihistamine', use: 'Allergy symptoms', category: 'Daily Life & Primary Care', rx: 'Prescription/availability varies', form: 'Oral/topical forms' },
  
  // Cardiology (52-101)
  { id: 52, name: 'Atorvastatin', group: 'Statin', use: 'High cholesterol; cardiovascular risk reduction', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 53, name: 'Rosuvastatin', group: 'Statin', use: 'High cholesterol; cardiovascular risk reduction', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 54, name: 'Simvastatin', group: 'Statin', use: 'High cholesterol', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 55, name: 'Pravastatin', group: 'Statin', use: 'High cholesterol', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 56, name: 'Ezetimibe', group: 'Cholesterol absorption inhibitor', use: 'High cholesterol', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 57, name: 'Fenofibrate', group: 'Fibrate', use: 'Hypertriglyceridemia', category: 'Cardiology', rx: 'Prescription', form: 'Capsules/tablets' },
  { id: 58, name: 'Gemfibrozil', group: 'Fibrate', use: 'Hypertriglyceridemia', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 59, name: 'Clopidogrel', group: 'Antiplatelet', use: 'Prevention of arterial thrombosis', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 60, name: 'Ticagrelor', group: 'Antiplatelet', use: 'Acute coronary syndrome; stent-related prevention', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 61, name: 'Prasugrel', group: 'Antiplatelet', use: 'Acute coronary syndrome with PCI', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 62, name: 'Warfarin', group: 'Vitamin K antagonist anticoagulant', use: 'Prevention/treatment of thromboembolism', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 63, name: 'Apixaban', group: 'Direct oral anticoagulant', use: 'Prevention/treatment of thromboembolism', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 64, name: 'Rivaroxaban', group: 'Direct oral anticoagulant', use: 'Prevention/treatment of thromboembolism', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 65, name: 'Dabigatran', group: 'Direct oral anticoagulant', use: 'Prevention/treatment of thromboembolism', category: 'Cardiology', rx: 'Prescription', form: 'Capsules' },
  { id: 66, name: 'Edoxaban', group: 'Direct oral anticoagulant', use: 'Prevention/treatment of thromboembolism', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 67, name: 'Enoxaparin', group: 'Low-molecular-weight heparin', use: 'Prevention/treatment of thrombosis', category: 'Cardiology', rx: 'Prescription', form: 'Injection' },
  { id: 68, name: 'Unfractionated heparin', group: 'Anticoagulant', use: 'Prevention/treatment of thrombosis', category: 'Cardiology', rx: 'Hospital/specialist use', form: 'Injection' },
  { id: 69, name: 'Nitroglycerin', group: 'Nitrate', use: 'Relief/prevention of angina', category: 'Cardiology', rx: 'Prescription', form: 'Sublingual tablet/spray; patch' },
  { id: 70, name: 'Isosorbide mononitrate', group: 'Nitrate', use: 'Angina prevention', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 71, name: 'Isosorbide dinitrate', group: 'Nitrate', use: 'Angina and heart failure adjunct', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; sublingual forms' },
  { id: 72, name: 'Amlodipine', group: 'Calcium-channel blocker', use: 'Hypertension; angina', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 73, name: 'Nifedipine', group: 'Calcium-channel blocker', use: 'Hypertension; angina', category: 'Cardiology', rx: 'Prescription', form: 'Extended-release tablets' },
  { id: 74, name: 'Diltiazem', group: 'Calcium-channel blocker', use: 'Hypertension; rate control; angina', category: 'Cardiology', rx: 'Prescription', form: 'Tablets/capsules; injection' },
  { id: 75, name: 'Verapamil', group: 'Calcium-channel blocker', use: 'Rate control; angina; hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 76, name: 'Metoprolol', group: 'Beta blocker', use: 'Hypertension; angina; arrhythmia; heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 77, name: 'Bisoprolol', group: 'Beta blocker', use: 'Hypertension; heart failure; angina', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 78, name: 'Carvedilol', group: 'Beta blocker', use: 'Heart failure; hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 79, name: 'Propranolol', group: 'Beta blocker', use: 'Arrhythmias; angina; hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; oral liquid; injection' },
  { id: 80, name: 'Atenolol', group: 'Beta blocker', use: 'Hypertension; angina', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 81, name: 'Nebivolol', group: 'Beta blocker', use: 'Hypertension; selected heart failure use', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 82, name: 'Labetalol', group: 'Alpha/beta blocker', use: 'Hypertension, including urgent settings', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 83, name: 'Enalapril', group: 'ACE inhibitor', use: 'Hypertension; heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; oral liquid' },
  { id: 84, name: 'Ramipril', group: 'ACE inhibitor', use: 'Hypertension; cardiovascular risk reduction', category: 'Cardiology', rx: 'Prescription', form: 'Capsules/tablets' },
  { id: 85, name: 'Lisinopril', group: 'ACE inhibitor', use: 'Hypertension; heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 86, name: 'Perindopril', group: 'ACE inhibitor', use: 'Hypertension; cardiovascular risk reduction', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 87, name: 'Losartan', group: 'ARB', use: 'Hypertension; heart failure; kidney protection in selected patients', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 88, name: 'Valsartan', group: 'ARB', use: 'Hypertension; heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 89, name: 'Telmisartan', group: 'ARB', use: 'Hypertension; cardiovascular risk reduction', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 90, name: 'Candesartan', group: 'ARB', use: 'Hypertension; heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 91, name: 'Sacubitril/valsartan', group: 'ARNI', use: 'Chronic heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 92, name: 'Furosemide', group: 'Loop diuretic', use: 'Fluid overload; heart failure; hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 93, name: 'Torsemide', group: 'Loop diuretic', use: 'Fluid overload and heart failure', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 94, name: 'Hydrochlorothiazide', group: 'Thiazide diuretic', use: 'Hypertension; edema', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 95, name: 'Indapamide', group: 'Thiazide-like diuretic', use: 'Hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 96, name: 'Spironolactone', group: 'Aldosterone antagonist', use: 'Heart failure; edema; hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 97, name: 'Eplerenone', group: 'Aldosterone antagonist', use: 'Heart failure; hypertension', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },
  { id: 98, name: 'Digoxin', group: 'Cardiac glycoside', use: 'Selected heart failure and atrial fibrillation', category: 'Cardiology', rx: 'Prescription', form: 'Tablets; injection; oral liquid' },
  { id: 99, name: 'Amiodarone', group: 'Antiarrhythmic', use: 'Selected cardiac arrhythmias', category: 'Cardiology', rx: 'Prescription/specialist', form: 'Tablets; injection' },
  { id: 100, name: 'Adenosine', group: 'Antiarrhythmic', use: 'Acute termination of certain supraventricular tachycardias', category: 'Cardiology', rx: 'Hospital use', form: 'Injection' },
  { id: 101, name: 'Ivabradine', group: 'Heart-rate lowering agent', use: 'Selected chronic heart failure or angina', category: 'Cardiology', rx: 'Prescription', form: 'Tablets' },

  // Neurology (102-151)
  { id: 102, name: 'Levetiracetam', group: 'Antiseizure medicine', use: 'Seizure disorders', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral solution; injection' },
  { id: 103, name: 'Valproic acid', group: 'Antiseizure medicine', use: 'Seizure disorders; selected migraine/bipolar uses', category: 'Neurology', rx: 'Prescription', form: 'Tablets/capsules; oral liquid; injection' },
  { id: 104, name: 'Carbamazepine', group: 'Antiseizure medicine', use: 'Seizure disorders; trigeminal neuralgia', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral suspension' },
  { id: 105, name: 'Oxcarbazepine', group: 'Antiseizure medicine', use: 'Focal seizures', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral suspension' },
  { id: 106, name: 'Lamotrigine', group: 'Antiseizure medicine', use: 'Seizure disorders; bipolar maintenance', category: 'Neurology', rx: 'Prescription', form: 'Tablets/chewables' },
  { id: 107, name: 'Topiramate', group: 'Antiseizure medicine', use: 'Seizure disorders; migraine prevention', category: 'Neurology', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 108, name: 'Phenytoin', group: 'Antiseizure medicine', use: 'Seizure disorders', category: 'Neurology', rx: 'Prescription', form: 'Capsules; oral suspension; injection' },
  { id: 109, name: 'Phenobarbital', group: 'Barbiturate antiseizure medicine', use: 'Seizure disorders', category: 'Neurology', rx: 'Prescription; controlled in some countries', form: 'Tablets; oral liquid; injection' },
  { id: 110, name: 'Clobazam', group: 'Benzodiazepine antiseizure medicine', use: 'Seizure disorders', category: 'Neurology', rx: 'Prescription; controlled in some countries', form: 'Tablets; oral liquid' },
  { id: 111, name: 'Gabapentin', group: 'Neuropathic pain/antiseizure medicine', use: 'Neuropathic pain; selected seizure disorders', category: 'Neurology', rx: 'Prescription', form: 'Capsules; tablets; oral solution' },
  { id: 112, name: 'Pregabalin', group: 'Neuropathic pain/antiseizure medicine', use: 'Neuropathic pain; fibromyalgia; seizures', category: 'Neurology', rx: 'Prescription', form: 'Capsules; oral solution' },
  { id: 113, name: 'Amitriptyline', group: 'Tricyclic antidepressant', use: 'Neuropathic pain; migraine prevention; depression', category: 'Neurology', rx: 'Prescription', form: 'Tablets' },
  { id: 114, name: 'Nortriptyline', group: 'Tricyclic antidepressant', use: 'Neuropathic pain; depression', category: 'Neurology', rx: 'Prescription', form: 'Capsules; tablets; oral liquid' },
  { id: 115, name: 'Duloxetine', group: 'SNRI', use: 'Neuropathic pain; anxiety/depression', category: 'Neurology', rx: 'Prescription', form: 'Capsules' },
  { id: 116, name: 'Venlafaxine', group: 'SNRI', use: 'Depression and anxiety', category: 'Neurology', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 117, name: 'Sertraline', group: 'SSRI', use: 'Depression and anxiety disorders', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral concentrate' },
  { id: 118, name: 'Escitalopram', group: 'SSRI', use: 'Depression and anxiety disorders', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral liquid' },
  { id: 119, name: 'Fluoxetine', group: 'SSRI', use: 'Depression and selected anxiety/compulsive disorders', category: 'Neurology', rx: 'Prescription', form: 'Capsules; tablets; oral liquid' },
  { id: 120, name: 'Mirtazapine', group: 'Antidepressant', use: 'Depression', category: 'Neurology', rx: 'Prescription', form: 'Tablets/ODT' },
  { id: 121, name: 'Clonazepam', group: 'Benzodiazepine', use: 'Selected seizure and panic disorders', category: 'Neurology', rx: 'Prescription; controlled in many countries', form: 'Tablets; oral liquid' },
  { id: 122, name: 'Lorazepam', group: 'Benzodiazepine', use: 'Seizure emergencies; anxiety; sedation', category: 'Neurology', rx: 'Prescription; controlled in many countries', form: 'Tablets; injection' },
  { id: 123, name: 'Diazepam', group: 'Benzodiazepine', use: 'Muscle spasm; seizures; selected anxiety disorders', category: 'Neurology', rx: 'Prescription; controlled in many countries', form: 'Tablets; rectal gel; injection' },
  { id: 124, name: 'Sumatriptan', group: 'Triptan', use: 'Acute migraine attacks', category: 'Neurology', rx: 'Prescription/OTC varies', form: 'Tablets; nasal spray; injection' },
  { id: 125, name: 'Rizatriptan', group: 'Triptan', use: 'Acute migraine attacks', category: 'Neurology', rx: 'Prescription', form: 'Tablets/ODT' },
  { id: 126, name: 'Zolmitriptan', group: 'Triptan', use: 'Acute migraine attacks', category: 'Neurology', rx: 'Prescription', form: 'Tablets; nasal spray' },
  { id: 127, name: 'Zonisamide', group: 'Antiseizure medicine', use: 'Focal seizures', category: 'Neurology', rx: 'Prescription', form: 'Capsules' },
  { id: 128, name: 'Flunarizine', group: 'Calcium-channel blocker', use: 'Migraine prevention in selected regions', category: 'Neurology', rx: 'Prescription where approved', form: 'Tablets' },
  { id: 129, name: 'Donepezil', group: 'Cholinesterase inhibitor', use: 'Symptomatic treatment of Alzheimer disease', category: 'Neurology', rx: 'Prescription', form: 'Tablets; ODT' },
  { id: 130, name: 'Rivastigmine', group: 'Cholinesterase inhibitor', use: 'Symptomatic treatment of Alzheimer/Parkinson dementia', category: 'Neurology', rx: 'Prescription', form: 'Capsules; patch; oral solution' },
  { id: 131, name: 'Galantamine', group: 'Cholinesterase inhibitor', use: 'Symptomatic treatment of Alzheimer disease', category: 'Neurology', rx: 'Prescription', form: 'Tablets; capsules; oral solution' },
  { id: 132, name: 'Memantine', group: 'NMDA receptor antagonist', use: 'Moderate-to-severe Alzheimer disease', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral solution' },
  { id: 133, name: 'Levodopa/carbidopa', group: 'Dopaminergic antiparkinsonian', use: 'Parkinson disease symptoms', category: 'Neurology', rx: 'Prescription', form: 'Tablets/capsules; intestinal formulations' },
  { id: 134, name: 'Pramipexole', group: 'Dopamine agonist', use: 'Parkinson disease; restless legs', category: 'Neurology', rx: 'Prescription', form: 'Tablets' },
  { id: 135, name: 'Ropinirole', group: 'Dopamine agonist', use: 'Parkinson disease; restless legs', category: 'Neurology', rx: 'Prescription', form: 'Tablets' },
  { id: 136, name: 'Rasagiline', group: 'MAO-B inhibitor', use: 'Parkinson disease', category: 'Neurology', rx: 'Prescription', form: 'Tablets' },
  { id: 137, name: 'Entacapone', group: 'COMT inhibitor', use: 'Parkinson disease with motor fluctuations', category: 'Neurology', rx: 'Prescription', form: 'Tablets' },
  { id: 138, name: 'Amantadine', group: 'Antiparkinsonian/antiviral', use: 'Parkinsonian symptoms; dyskinesia in selected use', category: 'Neurology', rx: 'Prescription', form: 'Capsules; tablets; oral solution' },
  { id: 139, name: 'Baclofen', group: 'Muscle relaxant', use: 'Spasticity', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral liquid; intrathecal formulation' },
  { id: 140, name: 'Tizanidine', group: 'Muscle relaxant', use: 'Spasticity', category: 'Neurology', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 141, name: 'Botulinum toxin type A', group: 'Neuromuscular blocker', use: 'Chronic migraine; dystonia; spasticity and other specialist indications', category: 'Neurology', rx: 'Specialist/hospital', form: 'Injection' },
  { id: 142, name: 'Methylprednisolone', group: 'Corticosteroid', use: 'Inflammatory neurologic conditions and other immune-mediated disorders', category: 'Neurology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 143, name: 'Mannitol', group: 'Osmotic agent', use: 'Raised intracranial pressure in selected emergencies', category: 'Neurology', rx: 'Hospital use', form: 'IV infusion' },
  { id: 144, name: 'Acetazolamide', group: 'Carbonic anhydrase inhibitor', use: 'Idiopathic intracranial hypertension; selected neurologic and other uses', category: 'Neurology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 145, name: 'Thiamine (vitamin B1)', group: 'Vitamin', use: 'Thiamine deficiency; neurologic complications of deficiency', category: 'Neurology', rx: 'OTC/prescription varies', form: 'Tablets; injection' },
  { id: 146, name: 'Pyridoxine (vitamin B6)', group: 'Vitamin', use: 'Vitamin B6 deficiency; selected neuropathy-related supplementation', category: 'Neurology', rx: 'OTC/prescription varies', form: 'Tablets; injection' },
  { id: 147, name: 'Cyanocobalamin (vitamin B12)', group: 'Vitamin', use: 'Vitamin B12 deficiency causing neurologic symptoms', category: 'Neurology', rx: 'OTC/prescription varies', form: 'Tablets; injection' },
  { id: 148, name: 'Lacosamide', group: 'Antiseizure medicine', use: 'Focal-onset seizures', category: 'Neurology', rx: 'Prescription', form: 'Tablets; oral solution; injection' },
  { id: 149, name: 'Methylcobalamin', group: 'Vitamin B12 analogue', use: 'Vitamin B12 supplementation; commonly used for deficiency-related neuropathy', category: 'Neurology', rx: 'OTC/prescription varies', form: 'Tablets; injection' },
  { id: 150, name: 'Lacosamide oral solution', group: 'Antiseizure medicine', use: 'Focal-onset seizures', category: 'Neurology', rx: 'Prescription', form: 'Oral solution' },
  { id: 151, name: 'Ethosuximide', group: 'Antiseizure medicine', use: 'Absence seizures', category: 'Neurology', rx: 'Prescription', form: 'Capsules; oral liquid' },

  // Pulmonology (152-201)
  { id: 152, name: 'Salbutamol (albuterol)', group: 'Short-acting beta2 agonist', use: 'Relief of bronchospasm', category: 'Pulmonology', rx: 'Prescription/OTC varies', form: 'Inhaler; nebulizer solution; tablets in some markets' },
  { id: 153, name: 'Terbutaline', group: 'Short-acting beta2 agonist', use: 'Bronchospasm', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler; nebulizer; tablets' },
  { id: 154, name: 'Ipratropium', group: 'Anticholinergic bronchodilator', use: 'COPD and bronchospasm', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler; nebulizer' },
  { id: 155, name: 'Tiotropium', group: 'Long-acting anticholinergic', use: 'COPD maintenance; selected asthma use', category: 'Pulmonology', rx: 'Prescription', form: 'Dry-powder/soft-mist inhaler' },
  { id: 156, name: 'Umeclidinium', group: 'Long-acting anticholinergic', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Dry-powder inhaler' },
  { id: 157, name: 'Aclidinium', group: 'Long-acting anticholinergic', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Dry-powder inhaler' },
  { id: 158, name: 'Glycopyrronium', group: 'Long-acting anticholinergic', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler/capsules' },
  { id: 159, name: 'Formoterol', group: 'Long-acting beta2 agonist', use: 'Asthma/COPD maintenance, usually in combination', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler; nebulizer' },
  { id: 160, name: 'Salmeterol', group: 'Long-acting beta2 agonist', use: 'Asthma/COPD maintenance, usually in combination', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 161, name: 'Indacaterol', group: 'Long-acting beta2 agonist', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 162, name: 'Olodaterol', group: 'Long-acting beta2 agonist', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Soft-mist inhaler' },
  { id: 163, name: 'Budesonide', group: 'Inhaled corticosteroid', use: 'Asthma/COPD maintenance; nasal allergy', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler; nebulizer; nasal spray' },
  { id: 164, name: 'Beclometasone', group: 'Inhaled corticosteroid', use: 'Asthma; allergic rhinitis', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler; nasal spray' },
  { id: 165, name: 'Fluticasone propionate', group: 'Inhaled corticosteroid', use: 'Asthma; allergic rhinitis', category: 'Pulmonology', rx: 'Prescription/OTC varies', form: 'Inhaler; nasal spray' },
  { id: 166, name: 'Mometasone', group: 'Corticosteroid', use: 'Asthma/allergic rhinitis; nasal inflammation', category: 'Pulmonology', rx: 'Prescription/OTC varies', form: 'Inhaler; nasal spray' },
  { id: 167, name: 'Ciclesonide', group: 'Inhaled corticosteroid', use: 'Asthma maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 168, name: 'Fluticasone furoate', group: 'Inhaled corticosteroid', use: 'Asthma/COPD maintenance; allergic rhinitis', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler; nasal spray' },
  { id: 169, name: 'Budesonide/formoterol', group: 'ICS/LABA combination', use: 'Asthma/COPD maintenance and reliever in selected regimens', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 170, name: 'Fluticasone/salmeterol', group: 'ICS/LABA combination', use: 'Asthma/COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 171, name: 'Fluticasone/vilanterol', group: 'ICS/LABA combination', use: 'Asthma/COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 172, name: 'Budesonide/glycopyrronium/formoterol', group: 'Triple inhaled therapy', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 173, name: 'Fluticasone/umeclidinium/vilanterol', group: 'Triple inhaled therapy', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },
  { id: 174, name: 'Montelukast', group: 'Leukotriene receptor antagonist', use: 'Asthma maintenance; allergic rhinitis', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; chewable tablets; granules' },
  { id: 175, name: 'Zafirlukast', group: 'Leukotriene receptor antagonist', use: 'Asthma maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets' },
  { id: 176, name: 'Theophylline', group: 'Methylxanthine bronchodilator', use: 'Selected chronic airway disease', category: 'Pulmonology', rx: 'Prescription', form: 'Extended-release tablets/capsules' },
  { id: 177, name: 'Acetylcysteine', group: 'Mucolytic', use: 'Thick respiratory mucus', category: 'Pulmonology', rx: 'OTC/prescription varies', form: 'Oral solution; nebulizer; inhalation forms' },
  { id: 178, name: 'Carbocisteine', group: 'Mucolytic', use: 'Chronic productive cough with mucus', category: 'Pulmonology', rx: 'Prescription/OTC varies', form: 'Capsules; syrup' },
  { id: 179, name: 'Dornase alfa', group: 'Mucolytic', use: 'Cystic fibrosis airway secretions', category: 'Pulmonology', rx: 'Prescription/specialist', form: 'Nebulizer solution' },
  { id: 180, name: 'Roflumilast', group: 'PDE-4 inhibitor', use: 'COPD with frequent exacerbations in selected patients', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets' },
  { id: 181, name: 'Pirfenidone', group: 'Antifibrotic', use: 'Idiopathic pulmonary fibrosis', category: 'Pulmonology', rx: 'Specialist prescription', form: 'Capsules/tablets' },
  { id: 182, name: 'Nintedanib', group: 'Antifibrotic', use: 'Idiopathic pulmonary fibrosis and selected progressive fibrosing interstitial lung diseases', category: 'Pulmonology', rx: 'Specialist prescription', form: 'Capsules' },
  { id: 183, name: 'Azithromycin', group: 'Macrolide antibiotic', use: 'Bacterial respiratory infections; selected chronic airway disease uses', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets/capsules; oral suspension; injection' },
  { id: 184, name: 'Amoxicillin', group: 'Penicillin antibiotic', use: 'Bacterial respiratory infections and other infections', category: 'Pulmonology', rx: 'Prescription', form: 'Capsules/tablets; oral suspension; injection' },
  { id: 185, name: 'Amoxicillin/clavulanate', group: 'Penicillin + beta-lactamase inhibitor', use: 'Bacterial respiratory infections', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; oral suspension; injection' },
  { id: 186, name: 'Doxycycline', group: 'Tetracycline antibiotic', use: 'Bacterial respiratory infections and other infections', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets/capsules; injection' },
  { id: 187, name: 'Levofloxacin', group: 'Fluoroquinolone antibiotic', use: 'Selected bacterial respiratory infections', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; IV infusion' },
  { id: 188, name: 'Cefuroxime', group: 'Cephalosporin antibiotic', use: 'Bacterial respiratory infections', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; oral suspension; injection' },
  { id: 189, name: 'Oseltamivir', group: 'Antiviral', use: 'Influenza treatment/prevention', category: 'Pulmonology', rx: 'Prescription', form: 'Capsules; oral suspension' },
  { id: 190, name: 'Nirmatrelvir/ritonavir', group: 'Antiviral combination', use: 'Selected high-risk COVID-19 treatment', category: 'Pulmonology', rx: 'Prescription', form: 'Oral tablets' },
  { id: 191, name: 'Prednisone', group: 'Systemic corticosteroid', use: 'Asthma/COPD exacerbations and inflammatory conditions', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; oral solution' },
  { id: 192, name: 'Prednisolone', group: 'Systemic corticosteroid', use: 'Airway inflammation and exacerbations', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; oral liquid; injection' },
  { id: 193, name: 'Dexamethasone', group: 'Systemic corticosteroid', use: 'Severe inflammatory respiratory conditions and other indications', category: 'Pulmonology', rx: 'Prescription/hospital', form: 'Tablets; injection' },
  { id: 194, name: 'Betamethasone', group: 'Corticosteroid', use: 'Inflammatory/allergic conditions in selected respiratory indications', category: 'Pulmonology', rx: 'Prescription', form: 'Tablets; injection; topical' },
  { id: 195, name: 'Magnesium sulfate', group: 'Electrolyte/bronchodilator adjunct', use: 'Severe acute asthma in selected emergencies', category: 'Pulmonology', rx: 'Hospital use', form: 'IV/IM injection' },
  { id: 196, name: 'Epinephrine', group: 'Adrenergic agonist', use: 'Anaphylaxis with respiratory compromise', category: 'Pulmonology', rx: 'Emergency medicine', form: 'Auto-injector; injection' },
  { id: 197, name: 'Acetylsalicylic acid', group: 'Analgesic/antiplatelet', use: 'Fever/pain; cardiovascular uses', category: 'Pulmonology', rx: 'OTC/prescription varies', form: 'Tablets' },
  { id: 198, name: 'Saline for nebulization', group: 'Airway humidification', use: 'Nebulization support and secretion mobilization', category: 'Pulmonology', rx: 'OTC', form: 'Nebulizer solution' },
  { id: 199, name: 'Oxygen (medical gas)', group: 'Medical gas', use: 'Treatment of hypoxemia', category: 'Pulmonology', rx: 'Medical supervision', form: 'Inhaled gas' },
  { id: 200, name: 'Levosalbutamol (levalbuterol)', group: 'Short-acting beta2 agonist', use: 'Relief of bronchospasm', category: 'Pulmonology', rx: 'Prescription/availability varies', form: 'Inhaler; nebulizer solution' },
  { id: 201, name: 'Aclidinium/formoterol', group: 'LABA/LAMA combination', use: 'COPD maintenance', category: 'Pulmonology', rx: 'Prescription', form: 'Inhaler' },

  // Gastroenterology (202-251)
  { id: 202, name: 'Pantoprazole', group: 'Proton-pump inhibitor', use: 'GERD; peptic ulcer disease', category: 'Gastroenterology', rx: 'Prescription/OTC varies', form: 'Tablets; injection' },
  { id: 203, name: 'Esomeprazole', group: 'Proton-pump inhibitor', use: 'GERD; ulcer disease', category: 'Gastroenterology', rx: 'Prescription/OTC varies', form: 'Capsules/tablets; injection' },
  { id: 204, name: 'Lansoprazole', group: 'Proton-pump inhibitor', use: 'GERD; ulcer disease', category: 'Gastroenterology', rx: 'Prescription/OTC varies', form: 'Capsules; oral suspension' },
  { id: 205, name: 'Rabeprazole', group: 'Proton-pump inhibitor', use: 'GERD; ulcer disease', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 206, name: 'Dexlansoprazole', group: 'Proton-pump inhibitor', use: 'GERD', category: 'Gastroenterology', rx: 'Prescription', form: 'Capsules' },
  { id: 207, name: 'Sucralfate', group: 'Mucosal protectant', use: 'Peptic ulcer disease', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets; suspension' },
  { id: 208, name: 'Bismuth subsalicylate', group: 'Antidiarrheal/ulcer therapy', use: 'Diarrhea; dyspepsia; H. pylori regimens', category: 'Gastroenterology', rx: 'OTC in many countries', form: 'Chewable tablets; liquid' },
  { id: 209, name: 'Metoclopramide', group: 'Prokinetic/antiemetic', use: 'Nausea; delayed gastric emptying', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets; oral liquid; injection' },
  { id: 210, name: 'Domperidone', group: 'Prokinetic/antiemetic', use: 'Selected nausea or motility disorders where approved', category: 'Gastroenterology', rx: 'Prescription; availability varies', form: 'Tablets; suspension' },
  { id: 211, name: 'Itopride', group: 'Prokinetic', use: 'Functional dyspepsia and delayed gastric emptying', category: 'Gastroenterology', rx: 'Prescription/availability varies', form: 'Tablets' },
  { id: 212, name: 'Mosapride', group: 'Prokinetic', use: 'Functional dyspepsia and motility disorders', category: 'Gastroenterology', rx: 'Prescription/availability varies', form: 'Tablets' },
  { id: 213, name: 'Hyoscine butylbromide', group: 'Antispasmodic', use: 'Abdominal cramping/spasm', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Tablets; injection' },
  { id: 214, name: 'Mebeverine', group: 'Antispasmodic', use: 'Irritable bowel syndrome symptoms', category: 'Gastroenterology', rx: 'Prescription/availability varies', form: 'Tablets/capsules' },
  { id: 215, name: 'Dicyclomine', group: 'Antispasmodic', use: 'Abdominal cramping and IBS symptoms', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets; capsule; syrup; injection' },
  { id: 216, name: 'Lubiprostone', group: 'Secretagogue', use: 'Chronic constipation; IBS-C in selected patients', category: 'Gastroenterology', rx: 'Prescription', form: 'Capsules' },
  { id: 217, name: 'Linaclotide', group: 'Guanylate cyclase-C agonist', use: 'IBS with constipation; chronic constipation', category: 'Gastroenterology', rx: 'Prescription', form: 'Capsules' },
  { id: 218, name: 'Plecanatide', group: 'Guanylate cyclase-C agonist', use: 'IBS with constipation; chronic constipation', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 219, name: 'Lactulose', group: 'Osmotic laxative', use: 'Constipation; hepatic encephalopathy', category: 'Gastroenterology', rx: 'Prescription/OTC varies', form: 'Oral solution' },
  { id: 220, name: 'Senna', group: 'Stimulant laxative', use: 'Constipation', category: 'Gastroenterology', rx: 'OTC', form: 'Tablets; tea/granules; oral liquid' },
  { id: 221, name: 'Sodium picosulfate', group: 'Stimulant laxative', use: 'Constipation; bowel preparation', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Tablets; oral solution' },
  { id: 222, name: 'Magnesium citrate', group: 'Saline laxative', use: 'Constipation; bowel preparation', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Oral solution' },
  { id: 223, name: 'Mesalazine (mesalamine)', group: '5-ASA anti-inflammatory', use: 'Ulcerative colitis', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets; granules; suppository; enema' },
  { id: 224, name: 'Sulfasalazine', group: '5-ASA/immune modulator', use: 'Ulcerative colitis; inflammatory bowel disease', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 225, name: 'Ozanimod', group: 'Sphingosine-1-phosphate receptor modulator', use: 'Ulcerative colitis in selected patients', category: 'Gastroenterology', rx: 'Specialist prescription', form: 'Capsules' },
  { id: 226, name: 'Beclometasone dipropionate', group: 'Corticosteroid', use: 'Selected inflammatory bowel disease formulations', category: 'Gastroenterology', rx: 'Prescription', form: 'Rectal preparations; topical forms' },
  { id: 227, name: 'Infliximab', group: 'TNF inhibitor', use: 'Inflammatory bowel disease and other immune-mediated disease', category: 'Gastroenterology', rx: 'Specialist prescription', form: 'IV infusion' },
  { id: 228, name: 'Adalimumab', group: 'TNF inhibitor', use: 'Inflammatory bowel disease and other immune-mediated disease', category: 'Gastroenterology', rx: 'Specialist prescription', form: 'Subcutaneous injection' },
  { id: 229, name: 'Ursodeoxycholic acid', group: 'Bile acid', use: 'Selected cholestatic liver diseases; gallstone dissolution in selected patients', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets/capsules; suspension' },
  { id: 230, name: 'Silymarin', group: 'Hepatoprotective supplement', use: 'Used as a supplement for liver health; evidence varies', category: 'Gastroenterology', rx: 'OTC/supplement', form: 'Capsules/tablets' },
  { id: 231, name: 'Tenofovir disoproxil fumarate', group: 'Antiviral', use: 'Chronic hepatitis B; HIV treatment combinations', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 232, name: 'Entecavir', group: 'Antiviral', use: 'Chronic hepatitis B', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 233, name: 'Sofosbuvir', group: 'Direct-acting antiviral', use: 'Hepatitis C treatment combinations', category: 'Gastroenterology', rx: 'Prescription/specialist', form: 'Tablets' },
  { id: 234, name: 'Velpatasvir', group: 'Direct-acting antiviral', use: 'Hepatitis C treatment combinations', category: 'Gastroenterology', rx: 'Prescription/specialist', form: 'Tablets' },
  { id: 235, name: 'Sofosbuvir/velpatasvir', group: 'Direct-acting antiviral combination', use: 'Hepatitis C', category: 'Gastroenterology', rx: 'Prescription/specialist', form: 'Tablets' },
  { id: 236, name: 'Rifaximin', group: 'Rifamycin antibiotic', use: 'Selected hepatic encephalopathy and infectious diarrhea indications', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 237, name: 'Vancomycin (oral)', group: 'Glycopeptide antibiotic', use: 'C. difficile colitis', category: 'Gastroenterology', rx: 'Prescription', form: 'Capsules; oral solution' },
  { id: 238, name: 'Metronidazole', group: 'Nitroimidazole antibiotic', use: 'Anaerobic and protozoal gastrointestinal infections', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets; oral suspension; IV' },
  { id: 239, name: 'Tinidazole', group: 'Nitroimidazole antimicrobial', use: 'Protozoal and anaerobic infections', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 240, name: 'Albendazole', group: 'Anthelmintic', use: 'Intestinal worm infections', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Tablets; oral suspension' },
  { id: 241, name: 'Mebendazole', group: 'Anthelmintic', use: 'Intestinal worm infections', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Tablets; chewable tablets' },
  { id: 242, name: 'Pyrantel', group: 'Anthelmintic', use: 'Pinworm and other intestinal worms', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Chewable tablets; suspension' },
  { id: 243, name: 'Orlistat', group: 'Lipase inhibitor', use: 'Obesity management in selected patients', category: 'Gastroenterology', rx: 'OTC/prescription varies', form: 'Capsules' },
  { id: 244, name: 'Pancrelipase', group: 'Pancreatic enzymes', use: 'Pancreatic exocrine insufficiency', category: 'Gastroenterology', rx: 'Prescription', form: 'Delayed-release capsules' },
  { id: 245, name: 'Vonoprazan', group: 'Potassium-competitive acid blocker', use: 'Acid-related disorders including GERD', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets' },
  { id: 246, name: 'Nizatidine', group: 'H2-receptor blocker', use: 'Acid-related disorders', category: 'Gastroenterology', rx: 'Prescription/availability varies', form: 'Capsules; oral liquid' },
  { id: 247, name: 'Balsalazide', group: '5-ASA prodrug', use: 'Ulcerative colitis', category: 'Gastroenterology', rx: 'Prescription', form: 'Capsules' },
  { id: 248, name: 'Mesalazine foam', group: '5-ASA topical formulation', use: 'Ulcerative colitis affecting the rectum/left colon', category: 'Gastroenterology', rx: 'Prescription', form: 'Rectal foam' },
  { id: 249, name: 'Tegaserod', group: 'Prokinetic/5-HT4 agonist', use: 'IBS with constipation in selected patients', category: 'Gastroenterology', rx: 'Specialist prescription', form: 'Tablets' },
  { id: 250, name: 'Fidaxomicin', group: 'Macrolide-like antibiotic', use: 'C. difficile infection', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets; oral suspension' },
  { id: 251, name: 'Vonoprazan/amoxicillin', group: 'Acid suppression + antibiotic regimen', use: 'H. pylori eradication regimen', category: 'Gastroenterology', rx: 'Prescription', form: 'Tablets/capsules' },

  // Orthopedics & Musculoskeletal (252-301)
  { id: 252, name: 'Celecoxib', group: 'COX-2 selective NSAID', use: 'Osteoarthritis and musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Capsules' },
  { id: 253, name: 'Etoricoxib', group: 'COX-2 selective NSAID', use: 'Arthritis and acute musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 254, name: 'Meloxicam', group: 'NSAID', use: 'Osteoarthritis and inflammatory pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets; oral suspension' },
  { id: 255, name: 'Ketorolac', group: 'NSAID', use: 'Short-term moderate acute pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription/hospital', form: 'Tablets; injection; ophthalmic forms' },
  { id: 256, name: 'Indomethacin', group: 'NSAID', use: 'Inflammatory arthritis and acute gout', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Capsules; suppositories; topical/ophthalmic forms' },
  { id: 257, name: 'Ketoprofen', group: 'NSAID', use: 'Musculoskeletal pain and inflammation', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription/OTC varies', form: 'Capsules; gel; topical forms' },
  { id: 258, name: 'Piroxicam', group: 'NSAID', use: 'Inflammatory arthritis and pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Capsules; gel' },
  { id: 259, name: 'Etodolac', group: 'NSAID', use: 'Osteoarthritis and inflammatory arthritis', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 260, name: 'Nimesulide', group: 'NSAID', use: 'Acute pain and inflammation in selected countries', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription/availability varies', form: 'Tablets; granules' },
  { id: 261, name: 'Aceclofenac', group: 'NSAID', use: 'Arthritic and musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets; topical gel' },
  { id: 262, name: 'Eperisone', group: 'Muscle relaxant', use: 'Muscle spasm associated with musculoskeletal disorders', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 263, name: 'Cyclobenzaprine', group: 'Muscle relaxant', use: 'Acute muscle spasm', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 264, name: 'Methocarbamol', group: 'Muscle relaxant', use: 'Muscle spasm and musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 265, name: 'Metaxalone', group: 'Muscle relaxant', use: 'Short-term acute musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 266, name: 'Dantrolene', group: 'Muscle relaxant', use: 'Spasticity; specialist use', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Capsules; injection' },
  { id: 267, name: 'Orphenadrine', group: 'Muscle relaxant', use: 'Painful muscle spasm', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 268, name: 'Thiocolchicoside', group: 'Muscle relaxant', use: 'Acute painful muscle spasm in selected regions', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets/capsules; injection; topical' },
  { id: 269, name: 'Colchicine', group: 'Anti-gout agent', use: 'Acute gout; gout prevention', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 270, name: 'Allopurinol', group: 'Xanthine oxidase inhibitor', use: 'Gout and hyperuricemia', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 271, name: 'Febuxostat', group: 'Xanthine oxidase inhibitor', use: 'Gout and hyperuricemia', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 272, name: 'Probenecid', group: 'Uricosuric', use: 'Chronic gout in selected patients', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 273, name: 'Alendronate', group: 'Bisphosphonate', use: 'Osteoporosis', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 274, name: 'Risedronate', group: 'Bisphosphonate', use: 'Osteoporosis', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 275, name: 'Ibandronate', group: 'Bisphosphonate', use: 'Osteoporosis', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 276, name: 'Zoledronic acid', group: 'Bisphosphonate', use: 'Osteoporosis and selected bone diseases', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription/hospital', form: 'IV infusion' },
  { id: 277, name: 'Denosumab', group: 'RANKL inhibitor', use: 'Osteoporosis and selected bone-loss conditions', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription/specialist', form: 'Subcutaneous injection' },
  { id: 278, name: 'Teriparatide', group: 'Parathyroid hormone analogue', use: 'Severe osteoporosis at high fracture risk', category: 'Orthopedics & Musculoskeletal', rx: 'Specialist prescription', form: 'Subcutaneous injection' },
  { id: 279, name: 'Abaloparatide', group: 'Parathyroid hormone-related analogue', use: 'Severe osteoporosis at high fracture risk', category: 'Orthopedics & Musculoskeletal', rx: 'Specialist prescription', form: 'Subcutaneous injection' },
  { id: 280, name: 'Calcitriol', group: 'Active vitamin D analogue', use: 'Selected calcium/bone disorders', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Capsules; oral liquid; injection' },
  { id: 281, name: 'Alfacalcidol', group: 'Vitamin D analogue', use: 'Selected bone/mineral disorders', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Capsules; oral drops' },
  { id: 282, name: 'Calcium gluconate', group: 'Calcium salt', use: 'Acute symptomatic hypocalcemia; emergency use', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription/hospital', form: 'Injection; oral products' },
  { id: 283, name: 'Raloxifene', group: 'Selective estrogen receptor modulator', use: 'Osteoporosis prevention/treatment in selected patients', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 284, name: 'Cholecalciferol', group: 'Vitamin D3', use: 'Vitamin D deficiency', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/prescription varies', form: 'Tablets; capsules; oral drops' },
  { id: 285, name: 'Ergocalciferol', group: 'Vitamin D2', use: 'Vitamin D deficiency', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/prescription varies', form: 'Capsules; oral liquid' },
  { id: 286, name: 'Vitamin K2 (menaquinone)', group: 'Vitamin supplement', use: 'Supplementation; evidence varies by indication', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/supplement', form: 'Capsules/tablets' },
  { id: 287, name: 'Glucosamine', group: 'Nutraceutical', use: 'Joint symptom support; evidence varies', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/supplement', form: 'Tablets/capsules' },
  { id: 288, name: 'Chondroitin sulfate', group: 'Nutraceutical', use: 'Joint symptom support; evidence varies', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/supplement', form: 'Capsules/tablets' },
  { id: 289, name: 'Topical diclofenac', group: 'Topical NSAID', use: 'Localized musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/prescription varies', form: 'Gel; patch' },
  { id: 290, name: 'Capsaicin', group: 'Topical analgesic', use: 'Localized neuropathic/musculoskeletal pain', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/prescription varies', form: 'Cream; patch' },
  { id: 291, name: 'Lidocaine', group: 'Local anesthetic', use: 'Local pain relief and anesthesia', category: 'Orthopedics & Musculoskeletal', rx: 'OTC/prescription varies', form: 'Cream/gel/patch; injection' },
  { id: 292, name: 'Methyl salicylate', group: 'Topical analgesic', use: 'Minor muscle/joint aches', category: 'Orthopedics & Musculoskeletal', rx: 'OTC', form: 'Cream; ointment; balm' },
  { id: 293, name: 'Menthol', group: 'Counterirritant', use: 'Minor muscle/joint aches', category: 'Orthopedics & Musculoskeletal', rx: 'OTC', form: 'Cream; gel; balm' },
  { id: 294, name: 'Trolamine salicylate', group: 'Topical salicylate', use: 'Minor muscle/joint pain', category: 'Orthopedics & Musculoskeletal', rx: 'OTC in some countries', form: 'Cream' },
  { id: 295, name: 'Hyaluronic acid', group: 'Viscosupplement', use: 'Intra-articular osteoarthritis symptom management in selected cases', category: 'Orthopedics & Musculoskeletal', rx: 'Specialist use', form: 'Injection' },
  { id: 296, name: 'Triamcinolone acetonide', group: 'Corticosteroid', use: 'Joint/soft-tissue inflammation; local injections', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Injection; topical forms' },
  { id: 297, name: 'Methylprednisolone acetate', group: 'Corticosteroid', use: 'Intra-articular and soft-tissue inflammation', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Injection' },
  { id: 298, name: 'Hydroxychloroquine', group: 'DMARD', use: 'Rheumatoid arthritis and selected autoimmune diseases', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription', form: 'Tablets' },
  { id: 299, name: 'Methotrexate', group: 'DMARD', use: 'Rheumatoid arthritis and other inflammatory diseases', category: 'Orthopedics & Musculoskeletal', rx: 'Specialist prescription', form: 'Tablets; injection' },
  { id: 300, name: 'Ropivacaine', group: 'Local anesthetic', use: 'Regional/local anesthesia and acute pain control', category: 'Orthopedics & Musculoskeletal', rx: 'Hospital/specialist', form: 'Injection' },
  { id: 301, name: 'Strontium ranelate', group: 'Bone-active medicine', use: 'Osteoporosis in selected countries/settings', category: 'Orthopedics & Musculoskeletal', rx: 'Prescription; use is restricted in some regions', form: 'Oral granules' },

  // Nephrology & Urology (302-350)
  { id: 302, name: 'Dapagliflozin', group: 'SGLT2 inhibitor', use: 'Type 2 diabetes; heart/kidney protection in selected patients', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 303, name: 'Empagliflozin', group: 'SGLT2 inhibitor', use: 'Type 2 diabetes; heart/kidney protection in selected patients', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 304, name: 'Canagliflozin', group: 'SGLT2 inhibitor', use: 'Type 2 diabetes; selected kidney/cardiovascular benefits', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 305, name: 'Finerenone', group: 'Nonsteroidal mineralocorticoid receptor antagonist', use: 'Chronic kidney disease associated with type 2 diabetes', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 306, name: 'Sodium bicarbonate', group: 'Alkali', use: 'Metabolic acidosis in selected kidney disease', category: 'Nephrology & Urology', rx: 'Prescription/OTC varies', form: 'Tablets; oral powder/solution' },
  { id: 307, name: 'Potassium chloride', group: 'Electrolyte', use: 'Potassium deficiency', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets/capsules; oral solution; IV' },
  { id: 308, name: 'Calcium acetate', group: 'Phosphate binder', use: 'Hyperphosphatemia in advanced chronic kidney disease', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 309, name: 'Sevelamer', group: 'Phosphate binder', use: 'Hyperphosphatemia in chronic kidney disease', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; powder' },
  { id: 310, name: 'Lanthanum carbonate', group: 'Phosphate binder', use: 'Hyperphosphatemia in chronic kidney disease', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Chewable tablets' },
  { id: 311, name: 'Patiromer', group: 'Potassium binder', use: 'Hyperkalemia', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Powder for oral suspension' },
  { id: 312, name: 'Sodium zirconium cyclosilicate', group: 'Potassium binder', use: 'Hyperkalemia', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Powder for oral suspension' },
  { id: 313, name: 'Epoetin alfa', group: 'Erythropoiesis-stimulating agent', use: 'Anemia of chronic kidney disease and other indications', category: 'Nephrology & Urology', rx: 'Specialist prescription', form: 'Injection' },
  { id: 314, name: 'Darbepoetin alfa', group: 'Erythropoiesis-stimulating agent', use: 'Anemia of chronic kidney disease and other indications', category: 'Nephrology & Urology', rx: 'Specialist prescription', form: 'Injection' },
  { id: 315, name: 'Iron sucrose', group: 'IV iron', use: 'Iron deficiency, including in chronic kidney disease', category: 'Nephrology & Urology', rx: 'Hospital/specialist', form: 'IV injection/infusion' },
  { id: 316, name: 'Ferric carboxymaltose', group: 'IV iron', use: 'Iron deficiency', category: 'Nephrology & Urology', rx: 'Prescription/hospital', form: 'IV injection/infusion' },
  { id: 317, name: 'Methylthiazide', group: 'Thiazide diuretic', use: 'Hypertension and edema', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 318, name: 'Bumetanide', group: 'Loop diuretic', use: 'Edema and fluid overload', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 319, name: 'Metolazone', group: 'Thiazide-like diuretic', use: 'Edema; selected resistant fluid overload', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 320, name: 'Ethacrynic acid', group: 'Loop diuretic', use: 'Edema when sulfonamide loop diuretics are unsuitable', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 321, name: 'Sodium polystyrene sulfonate', group: 'Potassium-binding resin', use: 'Hyperkalemia in selected settings', category: 'Nephrology & Urology', rx: 'Prescription/hospital', form: 'Oral powder/suspension' },
  { id: 322, name: 'Acetazolamide extended-release', group: 'Carbonic anhydrase inhibitor', use: 'Selected kidney stone/acid-base indications', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Capsules' },
  { id: 323, name: 'Amiloride', group: 'Potassium-sparing diuretic', use: 'Edema; hypertension; potassium conservation', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 324, name: 'Chlorthalidone', group: 'Thiazide-like diuretic', use: 'Hypertension', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 325, name: 'Triamterene', group: 'Potassium-sparing diuretic', use: 'Edema and hypertension', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Capsules/tablets' },
  { id: 326, name: 'Tamsulosin', group: 'Alpha-1 blocker', use: 'Benign prostatic hyperplasia symptoms', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Capsules/tablets' },
  { id: 327, name: 'Alfuzosin', group: 'Alpha-1 blocker', use: 'Benign prostatic hyperplasia symptoms', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Extended-release tablets' },
  { id: 328, name: 'Silodosin', group: 'Alpha-1 blocker', use: 'Benign prostatic hyperplasia symptoms', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Capsules' },
  { id: 329, name: 'Dutasteride', group: '5-alpha-reductase inhibitor', use: 'Benign prostatic hyperplasia', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Capsules' },
  { id: 330, name: 'Finasteride', group: '5-alpha-reductase inhibitor', use: 'Benign prostatic hyperplasia', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 331, name: 'Mirabegron', group: 'Beta-3 agonist', use: 'Overactive bladder', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Extended-release tablets' },
  { id: 332, name: 'Solifenacin', group: 'Antimuscarinic', use: 'Overactive bladder', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 333, name: 'Oxybutynin', group: 'Antimuscarinic', use: 'Overactive bladder', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; patch; gel' },
  { id: 334, name: 'Trospium', group: 'Antimuscarinic', use: 'Overactive bladder', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets/capsules' },
  { id: 335, name: 'Fesoterodine', group: 'Antimuscarinic', use: 'Overactive bladder', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Extended-release tablets' },
  { id: 336, name: 'Desmopressin', group: 'Vasopressin analogue', use: 'Central diabetes insipidus; selected nocturia indications', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; nasal spray; injection' },
  { id: 337, name: 'Nitrofurantoin', group: 'Urinary antibiotic', use: 'Uncomplicated urinary tract infection', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Capsules; oral liquid' },
  { id: 338, name: 'Fosfomycin', group: 'Urinary antibiotic', use: 'Uncomplicated urinary tract infection', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Oral sachet; IV formulations for selected infections' },
  { id: 339, name: 'Trimethoprim', group: 'Antibiotic', use: 'Urinary tract infections', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; oral liquid; injection' },
  { id: 340, name: 'Trimethoprim/sulfamethoxazole', group: 'Antibiotic combination', use: 'Urinary and other bacterial infections', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; oral suspension; injection' },
  { id: 341, name: 'Ciprofloxacin', group: 'Fluoroquinolone antibiotic', use: 'Selected urinary bacterial infections', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; IV; ophthalmic forms' },
  { id: 342, name: 'Methenamine hippurate', group: 'Urinary antiseptic', use: 'Prevention of recurrent urinary tract infection in selected patients', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 343, name: 'Potassium citrate', group: 'Urinary alkalinizer', use: 'Kidney stone prevention in selected stone types', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets; oral solution' },
  { id: 344, name: 'Sodium citrate', group: 'Urinary/systemic alkalinizer', use: 'Urinary alkalinization and selected metabolic conditions', category: 'Nephrology & Urology', rx: 'Prescription/OTC varies', form: 'Oral solution; tablets' },
  { id: 345, name: 'Benzbromarone', group: 'Uricosuric agent', use: 'Hyperuricemia/gout in selected countries', category: 'Nephrology & Urology', rx: 'Prescription/availability varies', form: 'Tablets' },
  { id: 346, name: 'Methazolamide', group: 'Carbonic anhydrase inhibitor', use: 'Selected glaucoma/pressure disorders and other specialist uses', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Tablets' },
  { id: 347, name: 'Tolvaptan', group: 'Vasopressin V2 antagonist', use: 'Selected hyponatremia; ADPKD specialist use', category: 'Nephrology & Urology', rx: 'Specialist prescription', form: 'Tablets' },
  { id: 348, name: 'Rituximab', group: 'Monoclonal antibody', use: 'Selected immune-mediated kidney diseases', category: 'Nephrology & Urology', rx: 'Specialist/hospital', form: 'IV infusion' },
  { id: 349, name: 'Mycophenolate mofetil', group: 'Immunosuppressant', use: 'Kidney transplant; selected glomerular diseases', category: 'Nephrology & Urology', rx: 'Specialist prescription', form: 'Tablets/capsules; oral suspension' },
  { id: 350, name: 'Vibegron', group: 'Beta-3 adrenergic agonist', use: 'Overactive bladder', category: 'Nephrology & Urology', rx: 'Prescription', form: 'Extended-release tablets' },

  // Other Common Specialist Medicines (351-400)
  { id: 351, name: 'Metformin', group: 'Biguanide', use: 'Type 2 diabetes', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; oral solution' },
  { id: 352, name: 'Gliclazide', group: 'Sulfonylurea', use: 'Type 2 diabetes', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; modified-release tablets' },
  { id: 353, name: 'Glimepiride', group: 'Sulfonylurea', use: 'Type 2 diabetes', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' },
  { id: 354, name: 'Sitagliptin', group: 'DPP-4 inhibitor', use: 'Type 2 diabetes', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' },
  { id: 355, name: 'Linagliptin', group: 'DPP-4 inhibitor', use: 'Type 2 diabetes', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' },
  { id: 356, name: 'Semaglutide', group: 'GLP-1 receptor agonist', use: 'Type 2 diabetes; obesity management in selected products', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Injection; oral tablet in selected products' },
  { id: 357, name: 'Liraglutide', group: 'GLP-1 receptor agonist', use: 'Type 2 diabetes; obesity management in selected patients', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Subcutaneous injection' },
  { id: 358, name: 'Insulin regular', group: 'Insulin', use: 'Diabetes requiring insulin', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Injection' },
  { id: 359, name: 'Insulin NPH', group: 'Intermediate-acting insulin', use: 'Diabetes requiring insulin', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Injection' },
  { id: 360, name: 'Insulin glargine', group: 'Long-acting insulin', use: 'Diabetes requiring basal insulin', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Injection' },
  { id: 361, name: 'Insulin lispro', group: 'Rapid-acting insulin', use: 'Diabetes requiring mealtime insulin', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Injection' },
  { id: 362, name: 'Levothyroxine', group: 'Thyroid hormone', use: 'Hypothyroidism', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; injection' },
  { id: 363, name: 'Carbimazole', group: 'Antithyroid medicine', use: 'Hyperthyroidism', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' },
  { id: 364, name: 'Propylthiouracil', group: 'Antithyroid medicine', use: 'Hyperthyroidism; selected specialist use', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' },
  { id: 365, name: 'Hydrocortisone', group: 'Corticosteroid', use: 'Adrenal insufficiency; inflammatory conditions', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; injection; topical forms' },
  { id: 366, name: 'Deflazacort', group: 'Corticosteroid', use: 'Inflammatory and immune-mediated conditions', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; oral liquid' },
  { id: 367, name: 'Methylprednisolone aceponate', group: 'Topical corticosteroid', use: 'Inflammatory skin disorders', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Cream/ointment' },
  { id: 368, name: 'Cefpodoxime', group: 'Cephalosporin antibiotic', use: 'Common bacterial infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; oral suspension' },
  { id: 369, name: 'Cefixime', group: 'Cephalosporin antibiotic', use: 'Bacterial infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets/capsules; oral suspension' },
  { id: 370, name: 'Ceftriaxone', group: 'Cephalosporin antibiotic', use: 'Serious bacterial infections', category: 'Other Common Specialist Medicines', rx: 'Hospital/prescription', form: 'Injection' },
  { id: 371, name: 'Cefalexin', group: 'Cephalosporin antibiotic', use: 'Bacterial infections of skin/urinary tract/respiratory tract', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Capsules; oral suspension' },
  { id: 372, name: 'Clarithromycin', group: 'Macrolide antibiotic', use: 'Respiratory and other bacterial infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets; oral suspension; injection' },
  { id: 373, name: 'Clindamycin', group: 'Lincosamide antibiotic', use: 'Bacterial infections including skin/dental/anaerobic infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Capsules; injection; topical' },
  { id: 374, name: 'Fluconazole', group: 'Antifungal', use: 'Candida and selected fungal infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Capsules/tablets; oral suspension; injection' },
  { id: 375, name: 'Amphotericin B', group: 'Antifungal', use: 'Serious systemic fungal infections', category: 'Other Common Specialist Medicines', rx: 'Hospital/specialist', form: 'IV infusion' },
  { id: 376, name: 'Valganciclovir', group: 'Antiviral', use: 'Selected cytomegalovirus infections', category: 'Other Common Specialist Medicines', rx: 'Specialist prescription', form: 'Tablets' },
  { id: 377, name: 'Valacyclovir', group: 'Antiviral', use: 'Herpes virus infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' },
  { id: 378, name: 'Antazoline/naphazoline eye drops', group: 'Ophthalmic antihistamine/decongestant', use: 'Allergic eye symptoms', category: 'Other Common Specialist Medicines', rx: 'OTC/prescription varies', form: 'Eye drops' },
  { id: 379, name: 'Carboxymethylcellulose', group: 'Artificial tears', use: 'Dry eye symptom relief', category: 'Other Common Specialist Medicines', rx: 'OTC', form: 'Eye drops' },
  { id: 380, name: 'Polyvinyl alcohol ophthalmic', group: 'Artificial tears', use: 'Dry eye symptom relief', category: 'Other Common Specialist Medicines', rx: 'OTC', form: 'Eye drops' },
  { id: 381, name: 'Timolol', group: 'Ophthalmic beta blocker', use: 'Glaucoma and ocular hypertension', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye drops' },
  { id: 382, name: 'Latanoprost', group: 'Prostaglandin analogue', use: 'Glaucoma and ocular hypertension', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye drops' },
  { id: 383, name: 'Brimonidine', group: 'Alpha-2 agonist', use: 'Glaucoma and ocular hypertension', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye drops' },
  { id: 384, name: 'Dorzolamide', group: 'Carbonic anhydrase inhibitor', use: 'Glaucoma and ocular hypertension', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye drops' },
  { id: 385, name: 'Travoprost', group: 'Prostaglandin analogue', use: 'Glaucoma and ocular hypertension', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye drops' },
  { id: 386, name: 'Moxifloxacin ophthalmic', group: 'Ophthalmic antibiotic', use: 'Bacterial eye infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye drops' },
  { id: 387, name: 'Erythromycin ophthalmic', group: 'Ophthalmic antibiotic', use: 'Bacterial eye/eyelid infections', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Eye ointment' },
  { id: 388, name: 'Ketotifen ophthalmic', group: 'Ophthalmic antihistamine', use: 'Allergic conjunctival symptoms', category: 'Other Common Specialist Medicines', rx: 'OTC/prescription varies', form: 'Eye drops' },
  { id: 389, name: 'Fluticasone propionate nasal', group: 'Intranasal corticosteroid', use: 'Allergic rhinitis', category: 'Other Common Specialist Medicines', rx: 'OTC/prescription varies', form: 'Nasal spray' },
  { id: 390, name: 'Budesonide nasal', group: 'Intranasal corticosteroid', use: 'Allergic rhinitis', category: 'Other Common Specialist Medicines', rx: 'OTC/prescription varies', form: 'Nasal spray' },
  { id: 391, name: 'Triamcinolone acetonide nasal', group: 'Intranasal corticosteroid', use: 'Allergic rhinitis', category: 'Other Common Specialist Medicines', rx: 'OTC/prescription varies', form: 'Nasal spray' },
  { id: 392, name: 'Mupirocin', group: 'Topical antibiotic', use: 'Localized bacterial skin infection', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Ointment/cream' },
  { id: 393, name: 'Fusidic acid', group: 'Topical antibiotic', use: 'Bacterial skin infection', category: 'Other Common Specialist Medicines', rx: 'Prescription/availability varies', form: 'Cream/ointment' },
  { id: 394, name: 'Benzoyl peroxide', group: 'Topical acne medicine', use: 'Acne', category: 'Other Common Specialist Medicines', rx: 'OTC in many countries', form: 'Gel/cream/wash' },
  { id: 395, name: 'Adapalene', group: 'Topical retinoid', use: 'Acne', category: 'Other Common Specialist Medicines', rx: 'OTC/prescription varies', form: 'Gel/cream' },
  { id: 396, name: 'Tretinoin', group: 'Topical retinoid', use: 'Acne and selected dermatologic conditions', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Cream/gel' },
  { id: 397, name: 'Isotretinoin', group: 'Systemic retinoid', use: 'Severe acne under specialist supervision', category: 'Other Common Specialist Medicines', rx: 'Specialist prescription', form: 'Capsules' },
  { id: 398, name: 'Ivermectin', group: 'Antiparasitic', use: 'Selected parasitic infections', category: 'Other Common Specialist Medicines', rx: 'Prescription/availability varies', form: 'Tablets; oral liquid' },
  { id: 399, name: 'Azathioprine', group: 'Immunosuppressant', use: 'Autoimmune diseases; transplant medicine', category: 'Other Common Specialist Medicines', rx: 'Specialist prescription', form: 'Tablets; injection' },
  { id: 400, name: 'Acarbose', group: 'Alpha-glucosidase inhibitor', use: 'Type 2 diabetes', category: 'Other Common Specialist Medicines', rx: 'Prescription', form: 'Tablets' }
];

console.log('Total raw medicines defined:', MEDICINES_RAW.length);
module.exports = { MEDICINES_RAW };
