import fs from 'fs';
import path from 'path';

// Complete dictionary of all 500 diseases organized by the 10 specialties
interface RawDiseaseDef {
  num: number;
  name: string;
  category: string;
  specialist: string;
  bodySystem: string;
  image: string;
  summary: string;
  quickFacts: {
    medicalName: string;
    commonName: string;
    diseaseType: string;
    bodySystem: string;
    commonAgeGroup: string;
    contagious: string;
    severity: string;
    curable: string;
    vaccineAvailable: string;
    commonRecoveryTime: string;
  };
  affectedBodyParts: string[];
  earlySymptoms: string[];
  commonSymptoms: string[];
  lessCommonSymptoms: string[];
  emergencyWarningSigns: string[];
  causes: string[];
  howDoesItSpread: string;
  riskFactors: string[];
  diagnosisMedicalHistory: string;
  diagnosisPhysicalExam: string;
  diagnosisAndTests: string[];
  homeCare: string[];
  symptomReliefMedicines: string[];
  treatments: string[];
  prevention: string[];
  complications: string[];
  recovery: string;
  whenToSeeDoctor: string;
  whenToSeekEmergencyCare: string;
}

// Specialty configuration
const SPECIALTIES = [
  {
    name: 'Cardiology',
    specialist: 'Cardiologist',
    system: 'Cardiovascular & Circulatory System',
    img: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Essential hypertension',
      'Pulmonary hypertension',
      'Hypertensive heart disease',
      'Coronary artery disease',
      'Stable angina',
      'Unstable angina',
      'Acute coronary syndrome',
      'ST-elevation myocardial infarction',
      'Non-ST-elevation myocardial infarction',
      'Myocardial infarction',
      'Atherosclerotic cardiovascular disease',
      'Ischemic heart disease',
      'Coronary vasospasm',
      'Coronary microvascular dysfunction',
      'Aortic stenosis',
      'Aortic regurgitation',
      'Mitral stenosis',
      'Mitral regurgitation',
      'Tricuspid stenosis',
      'Tricuspid regurgitation',
      'Pulmonary valve stenosis',
      'Pulmonary valve regurgitation',
      'Hypertrophic cardiomyopathy',
      'Dilated cardiomyopathy',
      'Restrictive cardiomyopathy',
      'Arrhythmogenic right ventricular cardiomyopathy',
      'Takotsubo cardiomyopathy',
      'Acute myocarditis',
      'Chronic myocarditis',
      'Pericarditis',
      'Pericardial effusion',
      'Cardiac tamponade',
      'Heart failure with reduced ejection fraction',
      'Heart failure with preserved ejection fraction',
      'Acute decompensated heart failure',
      'Right-sided heart failure',
      'Cor pulmonale',
      'Atrial fibrillation',
      'Atrial flutter',
      'Supraventricular tachycardia',
      'Ventricular tachycardia',
      'Ventricular fibrillation',
      'Premature ventricular contractions',
      'Premature atrial contractions',
      'Sick sinus syndrome',
      'Atrioventricular block',
      'Left bundle branch block',
      'Right bundle branch block',
      'Congenital heart disease',
      'Peripheral arterial disease'
    ]
  },
  {
    name: 'Neurology',
    specialist: 'Neurologist',
    system: 'Central & Peripheral Nervous System',
    img: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Ischemic stroke',
      'Hemorrhagic stroke',
      'Transient ischemic attack',
      'Subarachnoid hemorrhage',
      'Cerebral venous sinus thrombosis',
      'Carotid artery disease',
      'Multiple sclerosis',
      'Neuromyelitis optica',
      'Parkinson disease',
      'Huntington disease',
      'Alzheimer disease',
      'Vascular dementia',
      'Lewy body dementia',
      'Frontotemporal dementia',
      'Mild cognitive impairment',
      'Epilepsy',
      'Focal epilepsy',
      'Generalized epilepsy',
      'Status epilepticus',
      'Migraine',
      'Migraine with aura',
      'Cluster headache',
      'Tension-type headache',
      'Trigeminal neuralgia',
      'Glossopharyngeal neuralgia',
      'Bell palsy',
      'Facial nerve palsy',
      'Guillain-Barré syndrome',
      'Chronic inflammatory demyelinating polyneuropathy',
      'Myasthenia gravis',
      'Lambert-Eaton myasthenic syndrome',
      'Amyotrophic lateral sclerosis',
      'Spinal muscular atrophy',
      'Peripheral neuropathy',
      'Diabetic neuropathy',
      'Carpal tunnel syndrome',
      'Cervical radiculopathy',
      'Lumbar radiculopathy',
      'Sciatica',
      'Essential tremor',
      'Restless legs syndrome',
      'Narcolepsy',
      'Insomnia disorder',
      'Neurofibromatosis type 1',
      'Neurofibromatosis type 2',
      'Brain tumor',
      'Meningitis',
      'Encephalitis',
      'Hydrocephalus',
      'Normal pressure hydrocephalus'
    ]
  },
  {
    name: 'Pulmonology',
    specialist: 'Pulmonologist',
    system: 'Respiratory & Pulmonary System',
    img: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Asthma',
      'Severe asthma',
      'Chronic obstructive pulmonary disease',
      'Chronic bronchitis',
      'Emphysema',
      'Bronchiectasis',
      'Community-acquired pneumonia',
      'Hospital-acquired pneumonia',
      'Aspiration pneumonia',
      'Viral pneumonia',
      'Bacterial pneumonia',
      'Tuberculosis',
      'Nontuberculous mycobacterial lung disease',
      'Lung abscess',
      'Pleural effusion',
      'Empyema',
      'Pneumothorax',
      'Hemothorax',
      'Interstitial lung disease',
      'Idiopathic pulmonary fibrosis',
      'Hypersensitivity pneumonitis',
      'Sarcoidosis',
      'Pneumoconiosis',
      'Silicosis',
      'Asbestosis',
      "Coal workers' pneumoconiosis",
      'Occupational asthma',
      'Acute respiratory distress syndrome',
      'Acute respiratory failure',
      'Chronic respiratory failure',
      'Obstructive sleep apnea',
      'Central sleep apnea',
      'Obesity hypoventilation syndrome',
      'Pulmonary embolism',
      'Chronic thromboembolic pulmonary hypertension',
      'Pulmonary arterial hypertension',
      'Pulmonary edema',
      'Pulmonary alveolar proteinosis',
      'Cystic fibrosis',
      'Alpha-1 antitrypsin deficiency',
      'Bronchiolitis',
      'Acute bronchitis',
      'Lung nodule',
      'Lung cancer',
      'Mesothelioma',
      'Pleural plaques',
      'Pulmonary hemorrhage',
      'Pulmonary contusion',
      'Tracheobronchomalacia',
      'Vocal cord dysfunction'
    ]
  },
  {
    name: 'Gastroenterology',
    specialist: 'Gastroenterologist',
    system: 'Digestive & Gastrointestinal System',
    img: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Gastroesophageal reflux disease',
      'Barrett esophagus',
      'Esophagitis',
      'Achalasia',
      'Esophageal stricture',
      'Esophageal diverticulum',
      'Esophageal cancer',
      'Peptic ulcer disease',
      'Gastritis',
      'Helicobacter pylori infection',
      'Gastric outlet obstruction',
      'Gastric cancer',
      'Duodenitis',
      'Duodenal ulcer',
      'Celiac disease',
      'Irritable bowel syndrome',
      'Functional dyspepsia',
      'Inflammatory bowel disease',
      'Crohn disease',
      'Ulcerative colitis',
      'Microscopic colitis',
      'Diverticulosis',
      'Diverticulitis',
      'Acute appendicitis',
      'Chronic constipation',
      'Chronic diarrhea',
      'Intestinal obstruction',
      'Paralytic ileus',
      'Short bowel syndrome',
      'Colorectal cancer',
      'Colonic polyps',
      'Anal fissure',
      'Hemorrhoids',
      'Proctitis',
      'Pouchitis',
      'Cirrhosis',
      'Alcohol-associated liver disease',
      'Metabolic dysfunction-associated steatotic liver disease',
      'Metabolic dysfunction-associated steatohepatitis',
      'Autoimmune hepatitis',
      'Viral hepatitis A',
      'Viral hepatitis B',
      'Viral hepatitis C',
      'Primary biliary cholangitis',
      'Primary sclerosing cholangitis',
      'Hemochromatosis',
      'Wilson disease',
      'Acute pancreatitis',
      'Chronic pancreatitis',
      'Gallstone disease'
    ]
  },
  {
    name: 'Orthopedics',
    specialist: 'Orthopedist',
    system: 'Musculoskeletal & Skeletal System',
    img: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Primary osteoarthritis',
      'Knee osteoarthritis',
      'Hip osteoarthritis',
      'Shoulder osteoarthritis',
      'Post-traumatic osteoarthritis',
      'Rheumatoid arthritis',
      'Ankylosing spondylitis',
      'Psoriatic arthritis',
      'Gout',
      'Pseudogout',
      'Osteoporosis',
      'Osteomalacia',
      'Osteonecrosis',
      'Osteomyelitis',
      'Septic arthritis',
      'Fracture of femur',
      'Hip fracture',
      'Pelvic fracture',
      'Tibial fracture',
      'Fibular fracture',
      'Ankle fracture',
      'Patellar fracture',
      'Clavicle fracture',
      'Humerus fracture',
      'Radius fracture',
      'Ulna fracture',
      'Wrist fracture',
      'Hand fracture',
      'Foot fracture',
      'Vertebral compression fracture',
      'Scoliosis',
      'Kyphosis',
      'Lordosis',
      'Spinal stenosis',
      'Cervical spondylosis',
      'Lumbar spondylosis',
      'Herniated disc',
      'Degenerative disc disease',
      'Spondylolisthesis',
      'Rotator cuff tear',
      'Shoulder impingement syndrome',
      'Adhesive capsulitis',
      'Tennis elbow',
      "Golfer's elbow",
      'De Quervain tenosynovitis',
      'Trigger finger',
      'Bursitis',
      'Tendinitis',
      'Meniscal tear',
      'Anterior cruciate ligament injury'
    ]
  },
  {
    name: 'Nephrology',
    specialist: 'Nephrologist',
    system: 'Renal & Urinary System',
    img: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Acute kidney injury',
      'Chronic kidney disease',
      'End-stage kidney disease',
      'Diabetic kidney disease',
      'Hypertensive nephrosclerosis',
      'Glomerulonephritis',
      'IgA nephropathy',
      'Minimal change disease',
      'Focal segmental glomerulosclerosis',
      'Membranous nephropathy',
      'Membranoproliferative glomerulonephritis',
      'Rapidly progressive glomerulonephritis',
      'Acute interstitial nephritis',
      'Chronic interstitial nephritis',
      'Acute tubular injury',
      'Polycystic kidney disease',
      'Autosomal dominant polycystic kidney disease',
      'Alport syndrome',
      'Thin basement membrane disease',
      'Renal tubular acidosis',
      'Nephrotic syndrome',
      'Nephritic syndrome',
      'Nephrolithiasis',
      'Uric acid kidney stones',
      'Calcium oxalate kidney stones',
      'Struvite kidney stones',
      'Cystine kidney stones',
      'Hydronephrosis',
      'Obstructive uropathy',
      'Renal artery stenosis',
      'Renal vein thrombosis',
      'Renal cell carcinoma',
      'Wilms tumor',
      'Kidney infection',
      'Pyelonephritis',
      'Recurrent urinary tract infection',
      'Proteinuria',
      'Hematuria',
      'Electrolyte disorder',
      'Hyponatremia',
      'Hypernatremia',
      'Hypokalemia',
      'Hyperkalemia',
      'Hypocalcemia',
      'Hypercalcemia',
      'Metabolic acidosis',
      'Metabolic alkalosis',
      'Uremia',
      'Dialysis-related amyloidosis',
      'Kidney transplant rejection'
    ]
  },
  {
    name: 'Endocrinology',
    specialist: 'Endocrinologist',
    system: 'Endocrine & Metabolic System',
    img: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Type 1 diabetes mellitus',
      'Type 2 diabetes mellitus',
      'Gestational diabetes mellitus',
      'Prediabetes',
      'Diabetic ketoacidosis',
      'Hyperosmolar hyperglycemic state',
      'Diabetes insipidus',
      'Hypoglycemia',
      'Hyperglycemia',
      'Hypothyroidism',
      'Hashimoto thyroiditis',
      'Hyperthyroidism',
      'Graves disease',
      'Thyroiditis',
      'Thyroid nodule',
      'Goiter',
      'Thyroid cancer',
      'Medullary thyroid carcinoma',
      'Anaplastic thyroid carcinoma',
      'Primary hyperparathyroidism',
      'Cushing syndrome',
      'Cushing disease',
      'Addison disease',
      'Primary adrenal insufficiency',
      'Secondary adrenal insufficiency',
      'Congenital adrenal hyperplasia',
      'Pheochromocytoma',
      'Primary aldosteronism',
      'Acromegaly',
      'Growth hormone deficiency',
      'Gigantism',
      'Prolactinoma',
      'Hyperprolactinemia',
      'Hypopituitarism',
      'Diabetes due to endocrine disease',
      'Polycystic ovary syndrome',
      'Metabolic syndrome',
      'Obesity',
      'Vitamin D deficiency',
      'Rickets',
      'Osteoporosis due to endocrine disease',
      'Hypercortisolism',
      'Hypocortisolism',
      'Hyperaldosteronism',
      'Hypoaldosteronism',
      'Hyperparathyroidism',
      'Pituitary adenoma',
      'Adrenal adenoma',
      'Adrenal cancer',
      'Thyroid eye disease'
    ]
  },
  {
    name: 'Dermatology',
    specialist: 'Dermatologist',
    system: 'Integumentary & Cutaneous System',
    img: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Atopic dermatitis',
      'Contact dermatitis',
      'Seborrheic dermatitis',
      'Psoriasis',
      'Chronic urticaria',
      'Acne vulgaris',
      'Rosacea',
      'Perioral dermatitis',
      'Impetigo',
      'Cellulitis',
      'Erysipelas',
      'Folliculitis',
      'Furunculosis',
      'Scabies',
      'Pediculosis',
      'Tinea corporis',
      'Tinea cruris',
      'Tinea pedis',
      'Tinea capitis',
      'Onychomycosis',
      'Candidiasis of skin',
      'Pityriasis versicolor',
      'Viral warts',
      'Molluscum contagiosum',
      'Herpes zoster',
      'Herpes simplex skin infection',
      'Vitiligo',
      'Melasma',
      'Alopecia areata',
      'Androgenetic alopecia',
      'Telogen effluvium',
      'Hidradenitis suppurativa',
      'Lichen planus',
      'Lichen sclerosus',
      'Pemphigus vulgaris',
      'Bullous pemphigoid',
      'Dermatitis herpetiformis',
      'Erythema multiforme',
      'Stevens-Johnson syndrome',
      'Toxic epidermal necrolysis',
      'Erythema nodosum',
      'Panniculitis',
      'Keloid',
      'Hypertrophic scar',
      'Actinic keratosis',
      'Basal cell carcinoma of skin',
      'Squamous cell carcinoma of skin',
      'Melanoma',
      'Sebaceous cyst',
      'Epidermoid cyst'
    ]
  },
  {
    name: 'Infectious Disease',
    specialist: 'Infectious Disease Specialist',
    system: 'Immune & Pathogen Response System',
    img: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Influenza',
      'COVID-19',
      'Respiratory syncytial virus infection',
      'Measles',
      'Mumps',
      'Rubella',
      'Varicella',
      'Pertussis',
      'Diphtheria',
      'Tetanus',
      'Poliomyelitis',
      'Hepatitis E',
      'Hepatitis D',
      'HIV infection',
      'Acquired immunodeficiency syndrome',
      'Infectious mononucleosis',
      'Dengue fever',
      'Chikungunya',
      'Zika virus disease',
      'Yellow fever',
      'Japanese encephalitis',
      'West Nile virus infection',
      'Rabies',
      'Malaria',
      'Typhoid fever',
      'Cholera',
      'Shigellosis',
      'Amebiasis',
      'Giardiasis',
      'Leptospirosis',
      'Brucellosis',
      'Plague',
      'Anthrax',
      'Lyme disease',
      'Rocky Mountain spotted fever',
      'Rickettsial fever',
      'Q fever',
      'Toxoplasmosis',
      'Cytomegalovirus infection',
      'Epstein-Barr virus infection',
      'Hepatitis B infection',
      'Hepatitis C infection',
      'Syphilis',
      'Gonorrhea',
      'Chlamydia infection',
      'Genital herpes',
      'Human papillomavirus infection',
      'Candidemia',
      'Cryptococcosis',
      'Histoplasmosis'
    ]
  },
  {
    name: 'Oncology',
    specialist: 'Oncologist',
    system: 'Cellular & Neoplastic Biological System',
    img: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    diseases: [
      'Breast cancer',
      'Lung adenocarcinoma',
      'Small-cell lung cancer',
      'Non-small-cell lung cancer',
      'Pancreatic cancer',
      'Hepatocellular carcinoma',
      'Cholangiocarcinoma',
      'Gallbladder cancer',
      'Thyroid carcinoma',
      'Medullary thyroid carcinoma',
      'Anaplastic thyroid carcinoma',
      'Prostate cancer',
      'Bladder cancer',
      'Testicular cancer',
      'Ovarian cancer',
      'Endometrial cancer',
      'Cervical cancer',
      'Vulvar cancer',
      'Vaginal cancer',
      'Oral cavity cancer',
      'Laryngeal cancer',
      'Nasopharyngeal cancer',
      'Head and neck squamous cell carcinoma',
      'Soft tissue sarcoma',
      'Osteosarcoma',
      'Ewing sarcoma',
      'Glioblastoma',
      'Meningioma',
      'Acute lymphoblastic leukemia',
      'Acute myeloid leukemia',
      'Chronic lymphocytic leukemia',
      'Chronic myeloid leukemia',
      'Hodgkin lymphoma',
      'Diffuse large B-cell lymphoma',
      'Follicular lymphoma',
      'Multiple myeloma',
      'Myelodysplastic syndrome',
      'Myeloproliferative neoplasm',
      'Neuroblastoma',
      'Retinoblastoma',
      'Thymoma',
      'Merkel cell carcinoma',
      'Kaposi sarcoma',
      'Mesothelioma of peritoneum',
      'Choriocarcinoma',
      'Gestational trophoblastic neoplasia',
      'Acral lentiginous melanoma',
      'Cutaneous T-cell lymphoma',
      'Nasal cavity cancer',
      'Salivary gland cancer'
    ]
  }
];

export { SPECIALTIES };
